### ISSUE TITLE
Please update tor-browser snap

### ISSUE THREAD

**Issue by popey** [snapcrafters/tor-browser#3]
Latest version is 7.5a4 https://dist.torproject.org/torbrowser/

**Comment by baimafeima** [comment]
Is there some kind of coordination effort with the Tor Project itself in making Tor Browser available as a snap?

**Comment by Ads20000** [comment]
Doesn't look like anyone's asked them about it yet, would you know what way we should get in contact with them @baimafeima ? :)

**Comment by Ads20000** [comment]
[Latest stable seems to be 7.0.6](https://github.com/TheTorProject/gettorbrowser/releases/tag/v7.0.6) but I can't get to the actual site to get a link from there that we're using.
